apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.jetstack.io'
    chart: cert-manager
    targetRevision: v1.16.1
    helm:
       valueFiles:
        - https://raw.githubusercontent.com/SaremS/kubernetes-deployments/refs/heads/master/cluster/cert-manager/cert-manager-values.yaml  
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
