apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/SaremS/kubernetes-deployments'
    path: cluster/kafka
    targetRevision: master
    directory:
        include: kafka-cluster.yaml 
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: strimzi
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
  orphanedResources:
    ignore:
      - group: ""
        kind: PersistentVolumeClaim
