replicaCount: 1

image:
  name: ghcr.io/sarems/blog
  tag: 2024-11-09-22-36

persistence:
  storageClassName: null

tolerations: []
affinity: []

service:
  ports: []
  type: "ClusterIP"
  ipAddress: ~
