apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-tenant
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://operator.min.io'
    targetRevision: v6.0.3
    chart: tenant
    helm:
       valueFiles:
        - https://raw.githubusercontent.com/SaremS/kubernetes-deployments/refs/heads/master/cluster/minio/minio-tenant-values.yaml  
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: minio-tenant
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
