apiVersion: v1
kind: Service
metadata:
  name: quarto-blog-service
spec:
  selector:
    app: quarto-deployment
  ports:
    - protocol: TCP
      port: {{ .Values.loadBalancer.http.port }}         
      targetPort: {{ .Values.loadBalancer.http.targetPort }}
      name: http-port
    - protocol: TCP
      port: {{ .Values.loadBalancer.https.port }}         
      targetPort: {{ .Values.loadBalancer.https.targetPort }}
      name: https-port
  type: LoadBalancer
  loadBalancerIP: {{ .Values.loadBalancer.ipAddress }}

