apiVersion: v1
kind: Service
metadata:
  name: quarto-blog-service
spec:
  selector:
    app: quarto-deployment
  ports: {{ .Values.service.ports }}
  type: {{ .Values.service.type }}
  loadBalancerIP: {{ .Values.service.ipAddress }}

