apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: caddy-pvc
spec:
  accessModes:
    - ReadWriteMany
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: 1Gi
