apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.longhorn.io'
    targetRevision: 1.7.1
    helm:
      releaseName: longhorn
      values: |
        fullnameOverride: longhorn
        defaultSettings:
          taintToleration: "home=true:NoSchedule"
          priorityClass: system-node-critical
        longhornManager:
          tolerations:
              - effect: NoSchedule
                key: home
                operator: Exists
        longhornDriver:
          tolerations:
              - effect: NoSchedule
                key: home
                operator: Exists
        longhornUI:
          tolerations:
              - effect: NoSchedule
                key: home
                operator: Exists
        persistence:
          reclaimPolicy: Retain
    chart: longhorn
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: longhorn-system
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
