apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://metallb.github.io/metallb
      chart: metallb             
      targetRevision: 0.14.8
    - repoURL: https://github.com/SaremS/kubernetes-deployments
      path: cluster
      targetRevision: master
      directory:
        recurse: false 
        include: 'metallb-ip-pool.yaml'
  destination:
    server: https://kubernetes.default.svc  
    namespace: metallb                     
  syncPolicy:
    automated: {}
