apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: metallb
spec:
  project: default
  source:
    repoURL: https://github.com/metallb/metallb
    path: charts/metallb             
    targetRevision: v0.14.8
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc  
    namespace: default                     
  syncPolicy:
    automated: false
