apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blog
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SaremS/kubernetes-deployments
    path: blog/manifests
    targetRevision: master
    directory:
      recurse: false 
  destination:
    server: https://kubernetes.default.svc  
    namespace: blog                     
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
