createUserJob:
  useHelmHooks: false
  applyCustomEnv: false
migrateDatabaseJob:
  useHelmHooks: false
  applyCustomEnv: false

executor: "KubernetesExecutor"

workers:
  persistence:
    size: 10Gi
triggerer:
  persistence:
    size: 10Gi
logs:
  persistence:
    enabled: true
    size: 10Gi

dags:
  git-sync:
    enabled: true
