apiVersion: v1
kind: Service
metadata:
  name: quarto-blog-service
spec:
  selector:
    app: quarto-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
  loadBalancerIP: 192.169.0.1
