apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarto-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: quarto-deployment
  template:
    metadata:
      labels:
        app: quarto-deployment
    spec:
      serviceAccountName: job-trigger-sa
      securityContext:
        runAsUser: 0
        fsGroup: 0
      initContainers:
        - name: git-sync-init
          image: registry.k8s.io/git-sync/git-sync:v4.2.4
          volumeMounts:
            - name: quarto-static
              mountPath: /quarto
              readOnly: false
          env:
            - name: GITSYNC_REPO
              value: "https://github.com/SaremS/blog" 
            - name: GITSYNC_BRANCH
              value: "master" 
            - name: GITSYNC_ROOT
              value: /quarto
            - name: GITSYNC_PERIOD
              value: "5s"
            - name: GITSYNC_ONE_TIME
              value: "true"
            - name: "GITSYNC_GROUP_WRITE"
              value: "true"
        - name: quarto-init
          image: registry.gitlab.com/quarto-forge/docker/quarto 
          command: ['sh', '-c', 'sleep 5; while [ ! -f /quarto/blog/_quarto.yml ]; do echo "Waiting for git-sync-init to finish..." && sleep 5; done; quarto render /quarto/blog']
          volumeMounts:
            - name: quarto-static
              mountPath: /quarto
              readOnly: false
      containers:
        - name: caddy
          image: caddy:2.8.4-alpine
          ports:
          - containerPort: 80
          volumeMounts:
          - mountPath: /quarto
            name: quarto-static
            readOnly: true
          - mountPath: /etc/caddy/Caddyfile
            name: caddyfile
            subPath: Caddyfile
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000                      
            allowPrivilegeEscalation: false        
        - name: git-sync-sidecar
          image: registry.k8s.io/git-sync/git-sync:v4.2.4
          volumeMounts:
            - name: quarto-static
              mountPath: /quarto
              readOnly: false
          env:
            - name: GITSYNC_REPO
              value: "https://github.com/SaremS/blog" 
            - name: GITSYNC_BRANCH
              value: "master" 
            - name: GITSYNC_ROOT
              value: "/quarto"
            - name: GITSYNC_PERIOD
              value: "30s"
            - name: GITSYNC_GROUP_WRITE
              value: "true"
            - name: GITSYNC_EXECHOOK_COMMAND
              value: |
                curl -X POST https://kubernetes.default.svc/apis/batch/v1/namespaces/blog/jobs \
                  --header "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" \
                  --header "Content-Type: application/json" \
                  --cacert "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt" \
                  --data "{
                           \"apiVersion\": \"batch/v1\",
                           \"kind\": \"Job\",
                           \"metadata\": {
                             \"name\": \"quarto-render-job-$GITSYNC_HASH\"
                           },
                           \"spec\": {
                             \"ttlSecondsAfterFinished\": 900,
                             \"template\": {
                               \"spec\": {
                                 \"securityContext\": {
                                   \"runAsUser\": 0,
                                   \"fsGroup\": 0
                                 },
                                 \"containers\": [
                                   {
                                     \"name\": \"quarto-render\",
                                     \"image\": \"registry.gitlab.com/quarto-forge/docker/quarto\",
                                     \"command\": [\"sh\", \"-c\", \"quarto render /quarto/blog\"],
                                     \"volumeMounts\": [{\"name\": \"quarto\", \"mountPath\": \"/quarto\"}]
                                   }
                                 ],
                                 \"volumes\": [
                                   {
                                    \"name\": \"quarto\", 
                                    \"persistentVolumeClaim\": {
                                      \"claimName\": \"blog-pvc\"
                                    }
                                   }
                                 ],
                                 \"restartPolicy\": \"Never\"
                               }
                             }
                           }
                         }"
      volumes:
      - name: quarto-static
        persistentVolumeClaim:
          claimName: blog-pvc
      - name: caddyfile
        configMap:
          name: caddyfile
