apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarto-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: quarto-deployment
  template:
    metadata:
      labels:
        app: quarto-deployment
    spec:
      serviceAccountName: job-trigger-sa
      containers:
        - name: blog
          image: caddy:2.8.4-alpine
          ports:
          - containerPort: 80
            name: http-port
          - containerPort: 443
            name: https-port
          volumeMounts:
          - mountPath: /data/caddy
            name: caddy-data
            readOnly: false
          - mountPath: /etc/caddy/Caddyfile
            name: caddyfile
            subPath: Caddyfile
          securityContext:                  
            allowPrivilegeEscalation: false        
      volumes:
      - name: caddy-data
        persistentVolumeClaim:
          claimName: caddy-pvc
      - name: caddyfile
        configMap:
          name: caddyfile
