apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarto-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: quarto-deployment
  template:
    metadata:
      labels:
        app: quarto-deployment
    spec:
      serviceAccountName: job-trigger-sa
      containers:
        - name: blog
          image: ghcr.io/sarems/blog:2024-09-28-15-19
          ports:
          - containerPort: 80
            name: http-port
          - containerPort: 443
            name: https-port
          volumeMounts:
          - mountPath: /data/caddy
            name: caddy-data
            readOnly: false
          - mountPath: /etc/caddy/Caddyfile
            name: caddyfile
            subPath: Caddyfile
          securityContext:                  
            allowPrivilegeEscalation: false        
        - name: git-sync-sidecar
          securityContext:
            runAsUser: 0
          image: ghcr.io/sarems/kubernetes-deployments/git-sync-quarto-render:v0.0.7
          volumeMounts:
            - name: quarto-static
              mountPath: /quarto
              readOnly: false
          env:
            - name: GITSYNC_REPO
              value: "https://github.com/SaremS/blog" 
            - name: GITSYNC_BRANCH
              value: "master" 
            - name: GITSYNC_ROOT
              value: "/quarto"
            - name: GITSYNC_PERIOD
              value: "60s"
            - name: GITSYNC_GROUP_WRITE
              value: "true"
            - name: GITSYNC_EXECHOOK_COMMAND
              value: "/quarto-render-job"
      volumes:
      - name: quarto-static
        persistentVolumeClaim:
          claimName: blog-pvc
      - name: caddy-data
        persistentVolumeClaim:
          claimName: caddy-pvc
      - name: caddyfile
        configMap:
          name: caddyfile
