apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-trigger-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-trigger-role
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-trigger-rolebinding
subjects:
- kind: ServiceAccount
  name: job-trigger-sa
roleRef:
  kind: Role
  name: job-trigger-role
  apiGroup: rbac.authorization.k8s.io
