apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flink-kubernetes-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/apache/flink-kubernetes-operator
    targetRevision: release-1.9.0
    path: helm/flink-kubernetes-operator
    helm:
      values: |
        image:
          repository: apache/flink-kubernetes-operator
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: flink
  syncPolicy:
    syncOptions:
      - Validate=false
      - CreateNamespace=true
