apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blog
  namespace: argocd  
  annotations:
    argocd-image-updater.argoproj.io/image-list: blog=ghcr.io/sarems/blog 
    argocd-image-updater.argoproj.io/blog.update-strategy: alphabetical
spec:
  project: default
  sources:
    - repoURL: https://github.com/SaremS/kubernetes-deployments
      targetRevision: master 
      path: blog/quarto-blog 
    - repoURL: https://github.com/SaremS/kubernetes-deployments
      path: cluster/network_policies
      targetRevision: master
      directory:
        recurse: false
        include: 'frontend-policy.yaml'
  destination:
    server: 'https://kubernetes.default.svc' 
    namespace: blog-helm
  syncPolicy:
    automated:  
      selfHeal: true  
      prune: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
