apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.longhorn.io'
    targetRevision: v1.7.1
    chart: longhorn
    helm:
      values: |
        preUpgradeChecker:
          jobEnabled: false
        longhornManager:
          nodeSelector:
            longhorn-manager: use-node
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: longhorn-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
