apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-application
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  project: default
  source:
    repoURL: 'https://github.com/SaremS/kubernetes-deployments'
    targetRevision: master
    path: app_of_apps/apps
  syncPolicy:
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - Replace=true
    automated:
      prune: true
      selfHeal: true
