name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      build-target-folder:
        description: 'The folder containing the Dockerfile'
        required: true
      build-tag:
        description: 'The tag to apply to the built Docker image'
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build ghcr.io/sarems/kubernetes-deployments/${{ github.event.inputs.build-target-folder }} -t ${{ github.event.inputs.build-tag }} tools/${{ github.event.inputs.build-target-folder }}
    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Push Docker Image
      run: docker push ghcr.io/sarems/kubernetes-deployments/${{ github.event.inputs.build-target-folder }}:${{ github.event.inputs.build-tag }}
