name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      build-target-folder:
        description: 'The folder containing the Dockerfile'
        required: true
      build-tag:
        description: 'The tag to apply to the built Docker image'
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build and Publish latest Docker image
      uses: VaultVulp/gp-docker-action@1.5.0
      with:
        github-token: ${{ secrets.PUSH_IMAGE_KEY }}     
        image-name: ${{ github.event.inputs.build-target-folder }}:${{ github.event.inputs.build-tag}} 
        extract-git-tag: false
        build-context: tools/${{ github.event.inputs.build-target-folder }}
        dockerfile: ./Dockerfile  
